packages:
  - 'cloudflare'
  - 'cloudflare-d1'
  - 'parcel'
  - 'vite'
  - 'vite-static'

overrides:
  "react": "0.0.0-experimental-06e89951-20250620"
  "react-dom": "0.0.0-experimental-06e89951-20250620"
  "react-router": "0.0.0-experimental-14b5858e8"
